import { useEffect, useState } from "react";
import type { FileSummary } from "@ciphermesh/shared";
import type { PipelineStage } from "@ciphermesh/core";
import { deleteFile, downloadManifest, getFile } from "../lib/api";
import { filePipeline, mockStorage } from "../lib/pipeline";

export function FileDetails({ fileId, onChanged }: { fileId: string; onChanged(): void }) { const [file, setFile] = useState<(FileSummary & { objects: unknown[] })>(); const [error, setError] = useState(""); const [stage, setStage] = useState<PipelineStage>(); useEffect(() => { setFile(undefined); getFile(fileId).then(setFile).catch((e) => setError(e.message)); }, [fileId]); async function download() { setError(""); try { const manifest = await downloadManifest(fileId); const bytes = await filePipeline.download(manifest, setStage); const url = URL.createObjectURL(new Blob([bytes as Uint8Array<ArrayBuffer>], { type: manifest.mimeType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = manifest.originalName; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { setError(e instanceof Error ? e.message : "Reconstruction failed"); } finally { setStage(undefined); } }
  if (!file) return <aside className="panel details-panel">{error || "Loading file…"}</aside>;
  return <aside className="panel details-panel"><p className="eyebrow">File details</p><h2>{file.originalName}</h2><dl><div><dt>Original size</dt><dd>{file.originalSize.toLocaleString()} bytes</dd></div><div><dt>Encryption</dt><dd>{file.encryptionAlgorithm}</dd></div><div><dt>Erasure code</dt><dd>{file.dataShards} data + {file.parityShards} parity</dd></div><div><dt>Key threshold</dt><dd>{file.keyShareThreshold} of {file.keyShareCount}</dd></div><div><dt>Objects</dt><dd>{file.objects.length} across mock nodes</dd></div></dl>{stage && <p className="working">Reconstructing: {stage.replace("-", " ")}…</p>}{error && <p className="error">{error}</p>}<div className="actions"><button className="primary" disabled={file.status !== "available" || Boolean(stage)} onClick={download}>Reconstruct & download</button><button className="danger" onClick={async () => { if (!confirm("Delete this file and its local mock shards?")) return; const manifest = await downloadManifest(fileId).catch(() => null); if (manifest) await Promise.allSettled(manifest.objects.map((item) => mockStorage.deleteShard(item.nodeId, item.objectId))); await deleteFile(fileId); onChanged(); }}>Delete</button></div></aside>;
}
