import { lazy, Suspense } from "react";
import { BrandMark } from "./BrandMark";
import type { User } from "../lib/api";

export function Landing({ user, onEnter, onAuth }: { user: User | null; onEnter(): void; onAuth(): void }) {
  const enter = user ? onEnter : onAuth;
  return <main className="landing">
    <header className="landing-nav"><a className="landing-brand" href="/"><BrandMark small /><span>Horcrux</span></a><nav>{user ? <><span className="nav-user">{user.email}</span><button className="landing-link" onClick={onEnter}>Open archive ↗</button></> : <><button className="landing-link" onClick={onAuth}>Log in</button><button className="acid-button" onClick={onAuth}>Begin ↗</button></>}</nav></header>
    <section className="landing-hero"><div className="hero-copy"><p className="kicker">A distributed archive / 03 of 05 is enough</p><h1>Break the file.<br /><em>Not the promise.</em></h1><p className="hero-lede">Horcrux encrypts locally, divides one file across five independent nodes, and restores the whole when any three answer back.</p><div className="hero-actions"><button className="acid-button" onClick={enter}>{user ? "Open your archive" : "Protect a file"} ↗</button><a href="#method">Inspect the method ↓</a></div><div className="hero-proof">LOCAL ENCRYPTION <i /> 5-WAY PLACEMENT <i /> 3-OF-5 RECOVERY</div></div><div className="artifact" aria-label="A seal fractures into five pieces; two disappear and three reconstruct it"><div className="artifact-grid" /><Suspense fallback={<div className="artifact-fallback">✦</div>}><LazyFragmentHero /></Suspense><div className="artifact-readout"><span>05 fragments</span><span>02 absent</span><strong>03 sufficient</strong></div></div></section>
    <section className="ritual" id="method"><p className="kicker">The local ritual</p><ol className="ritual-line">{["compress", "encrypt", "split", "distribute"].map((stage, index) => <li key={stage}><b>0{index + 1}</b>{stage}</li>)}</ol><p>Plaintext never crosses the control plane. Neither do AES keys, Shamir share bodies, or encrypted shard bodies.</p></section>
    <section className="survival"><div><p className="kicker">Designed for absence</p><h2>Lose two.<br /><em>Keep everything.</em></h2><p>Five placements make room for two silent nodes. Any three surviving fragments reconstruct the original.</p></div><div className="recovery-map">{["01", "02", "03", "04", "05"].map((n, i) => <div className={`recovery-node ${i === 1 || i === 3 ? "is-lost" : ""}`} key={n}>NODE {n}<b>{i === 1 || i === 3 ? "×" : "✦"}</b></div>)}<div className="recovery-core">RESTORE<br /><small>03 / 05</small></div><p>two absent · three answer · archive restored</p></div></section>
    <section className="planes"><div><p className="kicker">Two planes. One boundary.</p><h2>The archive knows<br />where. <em>Not what.</em></h2></div><div className="plane-diagram"><div>BROWSER</div><p>metadata · auth · signaling <i /> <b>HONO / D1</b></p><p className="data">encrypted opaque object bytes ════════ NODE<br />══════════════════════════ NODE<br />══════════════════════════ NODE</p><small>The control plane coordinates identity and placement. Encrypted object bytes move directly between browser and storage nodes.</small></div></section>
    <section className="technical"><p className="kicker">Built for the long night</p><div className="technical-grid"><h2>Small mechanisms.<br /><em>Hard guarantees.</em></h2><dl>{[["01", "zstd + streamed frames", "Bounded work, frame by frame."], ["02", "AES-256-GCM", "Authenticated encryption before departure."], ["03", "Reed–Solomon 3+2", "Five shards; any three recover."], ["04", "Shamir 3-of-5", "The file key follows the same rule."]].map(([n, title, text]) => <div key={n}><dt>{n}</dt><dd><strong>{title}</strong><span>{text}</span></dd></div>)}</dl></div></section>
    <section className="landing-cta"><p className="kicker">Archive status / accepting files</p><h2>Keep the whole<br />in more than one place.</h2><button className="acid-button" onClick={enter}>{user ? "Open your archive" : "Create an archive"} ↗</button></section><footer><span>HORCRUX / LOCAL-FIRST DISTRIBUTED STORAGE</span><span>© {new Date().getFullYear()}</span></footer>
  </main>;
}
const LazyFragmentHero = lazy(() => import("./FragmentHero").then((module) => ({ default: module.FragmentHero })));
