import { ReedSolomonErasure } from "@subspace/reed-solomon-erasure.wasm";
import { concatBytes } from "./bytes";
export interface EncodedShards { shards: Uint8Array[]; shardSize: number; originalLength: number }
export interface ErasureCodingProvider { encode(data: Uint8Array, dataShards: number, parityShards: number): Promise<EncodedShards>; decode(shards: Array<Uint8Array | null>, dataShards: number, parityShards: number, originalLength: number): Promise<Uint8Array> }
export class WasmReedSolomonProvider implements ErasureCodingProvider {
  private instance?: Promise<ReedSolomonErasure>;
  constructor(private readonly create = () => ReedSolomonErasure.fromCurrentDirectory()) {}
  private ready() { return this.instance ??= this.create(); }
  async encode(data: Uint8Array, dataShards: number, parityShards: number): Promise<EncodedShards> { this.validate(dataShards, parityShards); const shardSize = Math.max(1, Math.ceil(data.byteLength / dataShards)); const contiguous = new Uint8Array(shardSize * (dataShards + parityShards)); contiguous.set(data); const result = (await this.ready()).encode(contiguous, dataShards, parityShards); if (result !== ReedSolomonErasure.RESULT_OK) throw new Error(`Reed-Solomon encoding failed (${result})`); return { shards: this.splitBuffer(contiguous, shardSize), shardSize, originalLength: data.byteLength }; }
  async decode(shards: Array<Uint8Array | null>, dataShards: number, parityShards: number, originalLength: number) { this.validate(dataShards, parityShards); if (shards.length !== dataShards + parityShards) throw new Error("Incorrect shard count"); const available = shards.filter((shard): shard is Uint8Array => shard !== null); if (available.length < dataShards) throw new Error(`Insufficient Reed-Solomon shards: need ${dataShards}, received ${available.length}`); const shardSize = available[0]!.byteLength; if (available.some((shard) => shard.byteLength !== shardSize)) throw new Error("Reed-Solomon shard sizes do not match"); const contiguous = new Uint8Array(shardSize * shards.length); shards.forEach((shard, index) => { if (shard) contiguous.set(shard, index * shardSize); }); const result = (await this.ready()).reconstruct(contiguous, dataShards, parityShards, shards.map(Boolean)); if (result !== ReedSolomonErasure.RESULT_OK) throw new Error(`Reed-Solomon reconstruction failed (${result})`); return concatBytes(this.splitBuffer(contiguous, shardSize).slice(0, dataShards), originalLength); }
  private splitBuffer(bytes: Uint8Array, size: number) { return Array.from({ length: bytes.byteLength / size }, (_, index) => bytes.slice(index * size, (index + 1) * size)); }
  private validate(data: number, parity: number) { if (!Number.isInteger(data) || !Number.isInteger(parity) || data < 1 || parity < 1 || data + parity > 256) throw new Error("Invalid Reed-Solomon parameters"); }
}
